### ISSUE TITLE
The send anonymized data option is not saving in configuration

### ISSUE THREAD

**Issue by valkjsaaa** [stanford-oval/almond-server#135] opened 2021-02-22 20:33 UTC
<img width="1002" alt="Screen Shot 2021-02-22 at 12 20 45 PM" src="https://user-images.githubusercontent.com/5488815/108766430-004b7500-750a-11eb-8b21-df74bcff3728.png">

This option will turn off every time I left this webpage.

**Comment by gcampax** [comment] 2021-02-22 21:52
I can't reproduce this: both in a Home Assistant add-on install, and running Almond from git, the checkbox is saved correctly. Did you click Save?

**Comment by valkjsaaa** [comment] 2021-02-22 23:36
https://user-images.githubusercontent.com/5488815/108784175-a2c42200-7523-11eb-88cc-41db0ba37be7.mov

yes. I did. is there any log file that I can dump for you to debug?

**Comment by gcampax** [comment] 2021-02-22 23:53
The addon log (from the addon page in the Supervisor tab) might have some relevant info.

**Comment by valkjsaaa** [comment] 2021-02-23 01:03
```
stats: size(charts[0][ctx_with_result_noquestion]) = 1
stats: size(charts[0][ctx_without_projection]) = 1
stats: size(charts[0][ctx_display_nonlist_result]) = 1
stats: size(charts[0][ctx_current_query]) = 1
stats: size(charts[0][ctx_thingpedia_result]) = 1
depth 0 took 0.01 seconds
--- DEPTH 1
stats: size(charts[1][constant_Any]) = 37
stats: size(charts[1][actionable_system_display_result_short]) = 1
depth 1 took 0.01 seconds
--- DEPTH 2
stats: size(charts[2][one_param_direct_result_info_phrase]) = 10
stats: size(charts[2][system_nonlist_result]) = 1
depth 2 took 0.00 seconds
--- DEPTH 3
stats: size(charts[3][$agent]) = 1
stats: size(charts[3][direct_result_info_phrase]) = 10
stats: size(charts[3][two_param_direct_result_info_phrase]) = 78
depth 3 took 0.02 seconds
--- DEPTH 4
stats: size(charts[4][direct_result_info_phrase]) = 78
stats: size(charts[4][three_param_direct_result_info_phrase]) = 456
stats: size(charts[4][system_nonlist_result]) = 17
depth 4 took 0.05 seconds
--- DEPTH 5
stats: size(charts[5][$agent]) = 17
stats: size(charts[5][direct_result_info_phrase]) = 456
stats: size(charts[5][system_nonlist_result]) = 108
depth 5 took 0.07 seconds
--- DEPTH 6
stats: size(charts[6][$agent]) = 108
stats: size(charts[6][system_nonlist_result]) = 510
depth 6 took 0.36 seconds
--- DEPTH 7
stats: size(charts[7][$agent]) = 510
depth 7 took 0.43 seconds
Agent act:
$dialogue @org.thingpedia.dialogue.transaction.sys_display_result;
Genie says: The current weather in Stanford, Palo Alto is sunny. The temperature is 64.9 F and the humidity is 45.3 %.
2021/02/23 00:07:00 [info] 249#249: *262 upstream timed out (110: Operation timed out) while proxying upgraded connection, client: 172.30.32.2, server: _, request: "GET /ws/conversation HTTP/1.1", upstream: "http://127.0.0.1:3000/ws/conversation", host: "stanforddorm.jackiehome.net:8123"
172.30.32.2 - - [23/Feb/2021:00:07:00 +0000] "GET /ws/conversation HTTP/1.1" 101 3345 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
2021/02/23 00:27:00 [info] 249#249: *286 upstream timed out (110: Operation timed out) while proxying upgraded connection, client: 172.30.32.2, server: _, request: "GET /ws/conversation HTTP/1.1", upstream: "http://127.0.0.1:3000/ws/conversation", host: "stanforddorm.jackiehome.net:8123"
172.30.32.2 - - [23/Feb/2021:00:27:00 +0000] "GET /ws/conversation HTTP/1.1" 101 2922 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
2021/02/23 00:47:00 [info] 249#249: *288 upstream timed out (110: Operation timed out) while proxying upgraded connection, client: 172.30.32.2, server: _, request: "GET /ws/conversation HTTP/1.1", upstream: "http://127.0.0.1:3000/ws/conversation", host: "stanforddorm.jackiehome.net:8123"
172.30.32.2 - - [23/Feb/2021:00:47:00 +0000] "GET /ws/conversation HTTP/1.1" 101 2922 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
172.30.32.2 - - [23/Feb/2021:01:02:44 +0000] "GET /ws/conversation HTTP/1.1" 101 2922 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET / 200 211.776 ms - 4395
172.30.32.2 - - [23/Feb/2021:01:03:01 +0000] "GET / HTTP/1.1" 200 1715 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
172.30.32.2 - - [23/Feb/2021:01:03:01 +0000] "GET /javascripts/validator.min.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/validator.min.js 304 1.931 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:01 +0000] "GET /stylesheets/bootstrap.min.css HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /stylesheets/bootstrap.min.css 304 4.093 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:01 +0000] "GET /javascripts/jstz.min.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/jstz.min.js 304 6.144 ms - -
GET /javascripts/shared.js 304 4.620 ms - -
GET /stylesheets/style.css 304 4.093 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:01 +0000] "GET /javascripts/shared.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
172.30.32.2 - - [23/Feb/2021:01:03:01 +0000] "GET /stylesheets/style.css HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /config 200 317.322 ms - 7121
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /config HTTP/1.1" 200 2383 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /javascripts/config.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/config.js 304 1.528 ms - -
GET /javascripts/config.js 304 1.933 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /javascripts/config.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /stylesheets/bootstrap.min.css HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /stylesheets/bootstrap.min.css 304 1.690 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /stylesheets/style.css HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /stylesheets/style.css 304 5.449 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /javascripts/validator.min.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/validator.min.js 304 1.222 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /javascripts/jstz.min.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/jstz.min.js 304 1.269 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /javascripts/qrcode.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/qrcode.js 304 1.555 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:02 +0000] "GET /javascripts/shared.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/shared.js 304 1.310 ms - -
GET /config 200 157.964 ms - 7121
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /config HTTP/1.1" 200 2382 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /stylesheets/bootstrap.min.css HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /stylesheets/bootstrap.min.css 304 1.695 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /stylesheets/style.css HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /stylesheets/style.css 304 1.324 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /javascripts/validator.min.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/validator.min.js 304 1.609 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /javascripts/shared.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/shared.js 304 1.609 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /javascripts/jstz.min.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/jstz.min.js 304 1.268 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /javascripts/qrcode.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/qrcode.js 304 1.125 ms - -
172.30.32.2 - - [23/Feb/2021:01:03:08 +0000] "GET /javascripts/config.js HTTP/1.1" 304 0 "https://stanforddorm.jackiehome.net:8123/api/hassio_ingress/T2lexzsW0YS0yexoAWedCiROTbey_f8ykBW4JidfJNA/config" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
GET /javascripts/config.js 304 1.107 ms - -
```

**Comment by valkjsaaa** [comment] 2021-02-23 01:04
There seems to be a few timed out requests. I'm not sure if that is relevant.

**Comment by valkjsaaa** [comment] 2021-02-23 01:04
My home assistant is running behind a reverse proxy. Could that be the problem?

**Comment by gcampax** [comment] 2021-02-23 01:50
That seems unlikely to be the problem (it's a normal POST request to save the configuration), but in general, are you on a different set up than the usual nginx reverse proxy set up by the Home Assistant Supervisor?

**Comment by gcampax** [comment] 2021-02-26 02:17
You mentioned that the latest version of the addon fixes recording. Does it fix this issue as well? Btw, I don't see any POST in the logs you posted, which is very weird.

**Comment by gcampax** [comment] 2021-03-03 04:03
Given that it seems to work here, and I haven't seen other reports of this, I'm going to go ahead and assume it was fixed by updating the add-on. Please reopen if you still experience this.

**Closed by gcampax** 2021-03-03 04:03 UTC
Labels: bug
